apiVersion: v2
name: ska-mid-cbf-int-tests
description: A Helm chart for Kubernetes MVP Mid
type: application
version: 0.13.0
appVersion: 0.13.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # Tango
  - name: ska-tango-base
    version: 0.4.13
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-base.enabled
  - name: ska-tango-util
    version: 0.4.13
    repository: https://artefact.skao.int/repository/helm-internal
  # CBF
  # Note: Versions and repository links defined here do not necessarily reflect what will be
  # deployed to the namespace. These values can be overwritten by Makefile processing at runtime
  # based on USE_DEV_BUILD and <repo>_HASH_VERSION variables.
  - name: ska-mid-cbf-mcs
    version: 1.1.1
    repository: https://gitlab.com/api/v4/projects/12488466/packages/helm/dev
    # To use a tagged version, update the version above and use the CAR repository below instead
    # repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-mcs.enabled
  - name: ska-mid-cbf-tmleafnode
    version: 1.1.1
    repository: https://gitlab.com/api/v4/projects/12488466/packages/helm/dev
    # To use a tagged version, update the version above and use the CAR repository below instead
    # repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-tmleafnode.enabled
  - name: ska-mid-cbf-engineering-console
    version: 1.0.1
    repository: https://gitlab.com/api/v4/projects/29657133/packages/helm/dev
    # To use a tagged version, update the version above and use the CAR repository below instead
    # repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-cbf-engineering-console.enabled
  # Taranta Suite
  - name: ska-tango-taranta
    version: 2.12
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.4.8
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-taranta-auth
    version: 0.2.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_auth_enabled
  # EDA
  - name: ska-tango-archiver
    version: 2.8.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-archiver.enabled
