display: ":0"
xauthority: "~/.Xauthority"

##### Global values #####

global:
  minikube: false
  operator: true
  exposeAllDS: true
  annotations:
    app.gitlab.com/app: ska-mid-cbf-int-tests
    app.gitlab.com/env: ska
  taranta_auth_enabled: false
  taranta_dashboard_enabled: true
  sub-system:
    tango-base:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-taranta:
      enabled: false
  retry:
    - "--sleep=3"
    - "--tries=100"
  tango_host: databaseds-tango-base:10000
  device_server_port: 45450
  cluster_domain: cluster.local

##### Mid CBF MCS Subchart values #####

mcsGeneral:
  version: 1.1.1
  helmRepository: https://artefact.skao.int/repository/helm-internal

ska-mid-cbf-mcs:
  enabled: true
  midcbf:
    image:
      # registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-mcs
      image: ska-mid-cbf-mcs
      tag: 1.1.1
      registry: artefact.skao.int
      pullPolicy: IfNotPresent
  hostInfo:
    environment: "mid-psi"
    clusterDomain: "cluster.local"
  # MCS timeout values in seconds
  controllerTimeout: 60
  fspTimeout: 15
  vccTimeout: 3
  lruTimeout: 60
  slimLinkTimeout: 10

ska-mid-cbf-tmleafnode:
  enabled: true
  midcbf:
    image:
      # registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-mcs
      image: ska-mid-cbf-mcs
      tag: 1.1.1
      registry: artefact.skao.int
      pullPolicy: IfNotPresent

##### Mid CBF EC Subchart values #####

ecGeneral:
  version: 1.1.1
  helmRepository: https://artefact.skao.int/repository/helm-internal

ska-mid-cbf-engineering-console:
  enabled: true
  engineeringconsole:
    image:
      # registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-engineering-console
      image: ska-mid-cbf-engineering-console
      tag: 1.1.1
      registry: artefact.skao.int
      pullPolicy: IfNotPresent

##### SKA Subchart values #####

skaGeneral:
  helmRepository: https://artefact.skao.int/repository/helm-internal

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: true

ska-tango-tangogql:
  enabled: true
  ska-tango-base:
    enabled: false

ska-taranta:
  legacy_compatibility: true
  enabled: true

ska-tango-util:
  enabled: true

ska-tango-archiver:
  enabled: false
  legacy_compatibility: true
  telescope: SKA-mid
  telescope_environment: MID_PSI
  hostname: timescaledb.ska-eda-mid-db.svc.cluster.local
  dbname: default_timescaledb
  dbuser: admin
  dbpassword: admin
  port: 5432
  configuration_manager: mid-eda/cm/01
  event_subscriber: mid-eda/es/01
  archwizard_config: MyHDB=tango://databaseds-tango-base.{{.Release.Name}}.svc.cluster.local:10000/mid-eda/cm/01
