.mid_kubernetes:
  variables:
    HELM_RELEASE: "test-$CI_PIPELINE_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"

.deploy:
  variables:
    K8S_AUTH_NAMESPACES: "$KUBE_NAMESPACE"
    K8S_AUTH_SERVICE_ACCOUNT: "ci-svc-int-tests-$CI_PIPELINE_ID"
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - make k8s-namespace KUBE_NAMESPACE=$KUBE_NAMESPACE
    - make k8s-namespace-credentials
    - make k8s-install-chart
    - echo "Get namespace resources"
    - make k8s-get
    - echo "Wait namespace resources"
    - make k8s-wait

.info:
  script:
    - echo "Get namespace resources"
    - make k8s-get
    - make k8s-vars
    - make k8s-info

.destroy:
  script: &destroy_script
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - make k8s-uninstall-chart || true
    - make k8s-delete-namespace

.redeploy:
  extends:
    - .deploy
  before_script: *destroy_script