include:
  - local: "/.gitlab/ci/common.gitlab-ci.yml"

.psi_mid_kubernetes:
  tags:
    - k8srunner-psi-mid
  extends:
    - .mid_kubernetes
  variables:
    INGRESS_HOST: "INGRESS.IP.ADDRESS"
    SERVICE_ACCOUNT: "ci-svc-int-tests-$CI_PIPELINE_ID"
  allow_failure: true

psi-mid-on-demand-deploy:
  stage: on_demand_psi
  extends:
    - .deploy
    - .psi_mid_kubernetes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME

psi-mid-on-demand-info:
  stage: on_demand_psi
  extends:
    - .info
    - .psi_mid_kubernetes
  rules:
    - when: manual
  allow_failure: true

psi-mid-on-demand-destroy:
  stage: on_demand_psi
  extends:
    - .destroy
    - .psi_mid_kubernetes
  needs:
    - job: psi-mid-on-demand-deploy
  rules:
    - when: manual
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME
    action: stop

psi-mid-auto-destroy:
  stage: cleanup
  extends:
    - .destroy
    - .psi_mid_kubernetes
  needs:
    - job: python-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: delayed
      start_in: 10 mins
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: delayed
      start_in: 2 hours
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME
    action: stop

psi-mid-on-demand-redeploy:
  stage: on_demand_psi
  extends:
    - .redeploy
    - .psi_mid_kubernetes
  needs:
    - job: psi-mid-on-demand-deploy
  rules:
    - when: manual
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME