include:
  - local: "/.gitlab/ci/common.gitlab-ci.yml"

.psi_mid_on_demand:
  tags:
    - k8srunner-psi-mid
  stage: on_demand_psi
  extends:
    - .mid
  allow_failure: true
  variables:
    VALUES: "values.yml"
    INGRESS_HOST: "INGRESS.IP.ADDRESS"
    SERVICE_ACCOUNT: "ci-svc-int-tests-$CI_PIPELINE_ID"

psi-mid-on-demand-deploy:
  extends:
    - .deploy
    - .psi_mid_on_demand
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
  allow_failure: true
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME

psi-mid-on-demand-info:
  extends:
    - .info
    - .psi_mid_on_demand
  allow_failure: true

psi-mid-on-demand-destroy:
  stage: cleanup
  extends:
    - .cleanup
    - .psi_mid_on_demand
  needs:
    - job: python-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: delayed
      start_in: 10 mins
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: delayed
      start_in: 2 hours
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME
    action: stop

psi-mid-on-demand-redeploy:
  extends:
    - .redeploy
    - .psi_mid_on_demand
  allow_failure: true
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME

